### ISSUE TITLE
deduce_plays() in bot_utils.py: ambiguous behavior for rainbow

### ISSUE THREAD

**Issue by ghutchings** [chikinn/hanabi#13]
Example: say my hand is [1r 2w 2? 1y 1b], and only 1w has been played. If I'm given the hints that 2w and 2? are 2 and w, right now the deduce_plays() routine would say that 2w and 2? are both legal plays.

The reason is that `for info in card['direct']:` only loops once for a value in suits, setting `suit` to `'w'`.

Probably the simplest fix is to require `info` to match two items in `suits` when ? is in `suits`, but can anyone think of a more elegant solution?

**Comment by chikinn** [comment]
Good catch.  I can't think of a more elegant way; fixing as you suggest.  I'll also check indirect info to conclude that a card is not rainbow.
